In [3]:
#1.Create a 3x3x3 array with random values
import numpy as np

random_array = np.random.rand(3, 3, 3)
print(random_array)

[[[0.76322217 0.00494209 0.63106607]
  [0.20347724 0.41184838 0.86703429]
  [0.50890907 0.16871147 0.55641327]]

 [[0.84546351 0.93808706 0.61257179]
  [0.15450619 0.56298573 0.49860084]
  [0.21231644 0.59920147 0.94018819]]

 [[0.96188925 0.52695579 0.00122143]
  [0.02707925 0.8215334  0.28046943]
  [0.07523962 0.6928292  0.33398616]]]


In [4]:
#2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
import numpy as np
matrix = np.zeros((5, 5))
#set values into diagonals 
matrix[1, 0] = 1
matrix[2, 1] = 2
matrix[3, 2] = 3
matrix[4, 3] = 4

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [5]:
#3.Create  8x8 matrix with checkerboard pattern 
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [8]:
#4.Normalize 5x5 matrix with random values
import numpy as np
nums = np.random.rand(5, 5)
print("Original array elements:")
print(nums)
# compute the mean of each column
col_means = np.mean(nums, axis=0)
# normalize each column by subtracting its mean and dividing by its standard deviation
arr_normalized = (nums - col_means) / np.std(nums, axis=0)
print("Original Array:")
print(nums)
print("\nNormalized Array (column-wise):")
print(arr_normalized)

Original array elements:
[[0.19683611 0.67746974 0.55083271 0.86619853 0.70513698]
 [0.551561   0.38753848 0.24059334 0.20775666 0.49579872]
 [0.96654635 0.11549512 0.43480223 0.01248744 0.40104287]
 [0.91397572 0.32703331 0.7431164  0.2620001  0.91033234]
 [0.58709626 0.30116793 0.59526826 0.14919431 0.40320958]]
Original Array:
[[0.19683611 0.67746974 0.55083271 0.86619853 0.70513698]
 [0.551561   0.38753848 0.24059334 0.20775666 0.49579872]
 [0.96654635 0.11549512 0.43480223 0.01248744 0.40104287]
 [0.91397572 0.32703331 0.7431164  0.2620001  0.91033234]
 [0.58709626 0.30116793 0.59526826 0.14919431 0.40320958]]

Normalized Array (column-wise):
[[-1.60100624  1.73351349  0.22537363  1.91912633  0.6177777 ]
 [-0.32869716  0.14164185 -1.61898272 -0.31079696 -0.44197363]
 [ 1.15975108 -1.35201595 -0.46442137 -0.97210875 -0.92166443]
 [ 0.97119341 -0.19056258  1.36848985 -0.12709248  1.65655607]
 [-0.20124109 -0.33257681  0.48954061 -0.50912813 -0.91069572]]


In [11]:
#5.Finding common values between arrays
import numpy as np
array1 = np.array([0, 1, 3, 4, 40])
print("Array1: ",array1)
array2 = [80, 3, 4]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0  1  3  4 40]
Array2:  [80, 3, 4]
Common values between two arrays:
[3 4]


In [12]:
#6.How to find date of today tommorrow and yesterday 
import numpy as np 
# for today
today = np.datetime64('today', 'D')
print("Today: ", today)  
# for yesterday
yesterday = np.datetime64('today', 'D')
- np.timedelta64(1, 'D')  
print("Yestraday: ", yesterday)  
# for tomorrow
tomorrow = np.datetime64('today', 'D')
+ np.timedelta64(1, 'D')  
print("Tomorrow: ", tomorrow)

Today:  2023-09-21
Yestraday:  2023-09-21
Tomorrow:  2023-09-21


In [19]:
#7.Consider two array A and B check if they are equal 
arr = np.array([22,33,44])
arr1 = np.array([22,33,44])
np.array_equal(arr, arr1)
print((arr == arr1).all())


True


In [23]:
# 8.Create random vector of size 10 and replace the maximum value by 0
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.99882871 0.20666824 0.41417504 0.56549604 0.46463924 0.73742227
 0.71137242 0.19369625 0.12867303 0.94733709]
Maximum value replaced by 0:
[0.         0.20666824 0.41417504 0.56549604 0.46463924 0.73742227
 0.71137242 0.19369625 0.12867303 0.94733709]


In [27]:
#9.Print all the values of the array 
import numpy as np
my_array1= np.array([1, 2, 3, 4, 5])
my_array2=np.array([2,2,2,2,2])
print(my_array1)
print(my_array2)


[1 2 3 4 5]
[2 2 2 2 2]


In [28]:
#10.Subtract the mean of each row of a matrix 
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.05963191 0.37440381 0.85859987 0.08458162 0.34558933 0.76825316
  0.84830236 0.22009009 0.68922581 0.75119979]
 [0.42568085 0.95179641 0.10737728 0.1913737  0.13634191 0.25152556
  0.62436398 0.93469468 0.11081179 0.14353123]
 [0.18645437 0.3146436  0.87385855 0.15428111 0.78531491 0.82565802
  0.1537571  0.8513909  0.37583201 0.49915097]
 [0.914145   0.77560848 0.96492498 0.23909345 0.93449026 0.47741377
  0.32016039 0.27889982 0.21631932 0.7686557 ]
 [0.33555891 0.41248795 0.22179923 0.56053241 0.4257575  0.00176013
  0.00651581 0.67520862 0.24773597 0.58035526]]

Subtract the mean of each row of the said matrix:

[[-0.44035587 -0.12558396  0.35861209 -0.41540615 -0.15439844  0.26826538
   0.34831458 -0.27989769  0.18923803  0.25121202]
 [ 0.03793111  0.56404667 -0.28037246 -0.19637604 -0.25140783 -0.13622418
   0.23661424  0.54694494 -0.27693795 -0.24421851]
 [-0.31557978 -0.18739055  0.37182439 -0.34775304  0.28328075  0.32362387
  -0.34827705  0.34935674 -0.1

In [29]:
#11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?
import numpy as np
initial_vector = np.array([2,3,4,5,6])
indices = np.array([1, 3, 3, 4])
unique_indices = np.unique(indices)
initial_vector[unique_indices] += 1
print(initial_vector)

[2 4 4 6 7]


In [32]:
#12.How to get the diagonal of a dot product? using numpy
import numpy as np
matrix1 = np.array([[3,4 ], [3, 4]])
matrix2 = np.array([[5, 6], [9, 9]])
dot_product = np.dot(matrix1, matrix2)
diagonal = np.diag(dot_product)
print(diagonal)

[51 54]


In [34]:
13.How to find the most frequent value in an array?
import numpy as np

def most_frequent(arr):
    unique_elements, counts = np.unique(arr, return_counts=True)
    most_frequent_element = unique_elements[np.argmax(counts)]
    return most_frequent_element
my_array = np.array([1, 2, 222,2,2,2,2,2,2,2,2,2,2, 3, 2,4,4,4,4,4,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5,5,5,6,6,6,6,6,6,6,6,6,6,6,6,6])
result = most_frequent(my_array)
print("The most frequent element is:", result)

The most frequent element is: 4


In [38]:
#14.How to get the n largest values of an array
import numpy as np
my_array = np.array([5, 2, 99, 1, 5, 6])
n = 1
n_largest_values = np.partition(my_array, -n)[-n:]

print(n_largest_values)


[99]


In [41]:
#15.How to create a record array from a regular array?
import numpy as np
regular_array = np.array([(1, 'eragantla', 25),
                          (2, 'phani', 30),
                          (3, 'reddy', 35)],
                         dtype=[('ID', int), ('Name', 'U10'), ('Age', int)])
print(regular_array['ID'])
print(regular_array['Name'])
print(regular_array['Age'])

[1 2 3]
['eragantla' 'phani' 'reddy']
[25 30 35]


In [42]:
#16. How to swap two rows of an array?
import numpy as np
arr = np.array([[4,3,1], [5,7,0], [9,9,3], [8,2,4]])
print("Original aarray:\n",arr,"\n")
arr[[0,2]] = arr[[2,0]]#swapping 
print("Result:\n",arr)

Original aarray:
 [[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]] 

Result:
 [[9 9 3]
 [5 7 0]
 [4 3 1]
 [8 2 4]]


In [45]:
#17. Write python code to reshape to the next dimension of numpy array?
import numpy as np
arr_3d = np.array([[[1, 2,9], [3, 4,10]], [[5, 6,11], [7, 8,12]]])
reshaped_arr = arr_3d.reshape(-1, arr_3d.shape[1], arr_3d.shape[2], 1)
print(reshaped_arr)

[[[[ 1]
   [ 2]
   [ 9]]

  [[ 3]
   [ 4]
   [10]]]


 [[[ 5]
   [ 6]
   [11]]

  [[ 7]
   [ 8]
   [12]]]]
